// Generated automatically by nearley, version 2.19.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "string", "symbols": [{"literal":"\""}, "characters", {"literal":"\""}], "postprocess": 
        (data) => (data[1]).toString()
        },
    {"name": "characters", "symbols": ["character"], "postprocess": id},
    {"name": "characters", "symbols": ["character", "characters"], "postprocess": (data) => data[0] + data[1]},
    {"name": "character", "symbols": [/[^/";]/], "postprocess": id},
    {"name": "float", "symbols": ["int", {"literal":"."}, "int"], "postprocess": data => {return parseFloat(data[0] + data[1] + data[2])}},
    {"name": "float", "symbols": ["int"], "postprocess": data => {return parseInt(data[0])}},
    {"name": "int$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "int$ebnf$1", "symbols": ["int$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "int", "symbols": ["int$ebnf$1"], "postprocess": data => {return data[0].join(""); }},
    {"name": "bool$string$1", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "bool", "symbols": ["bool$string$1"], "postprocess": data => "b#" + data[0]},
    {"name": "bool$string$2", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "bool", "symbols": ["bool$string$2"], "postprocess": data => "b#" + data[0]},
    {"name": "value", "symbols": ["string"], "postprocess": id},
    {"name": "value", "symbols": ["characters"], "postprocess": id},
    {"name": "value", "symbols": ["float"], "postprocess": id},
    {"name": "value", "symbols": ["int"], "postprocess": id},
    {"name": "value", "symbols": ["bool"], "postprocess": id},
    {"name": "value", "symbols": ["expression"], "postprocess": id},
    {"name": "value", "symbols": ["identifier"], "postprocess": id},
    {"name": "identifier$ebnf$1", "symbols": [/[a-zA-Z0-9_]/]},
    {"name": "identifier$ebnf$1", "symbols": ["identifier$ebnf$1", /[a-zA-Z0-9_]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "identifier", "symbols": [{"literal":"@"}, "identifier$ebnf$1"], "postprocess": data => data[0] + data[1].join("")},
    {"name": "expression", "symbols": ["_", "AS", "_"], "postprocess": data => {return data[1]; }},
    {"name": "expression", "symbols": ["element", "_", "comparison_operator", "_", "element"], "postprocess": 
        d => ({
            type: "comparison",
            operator: d[2],
            left: d[0],
            right: d[4]
        })
                },
    {"name": "comparison_operator", "symbols": [{"literal":">"}], "postprocess": id},
    {"name": "comparison_operator$string$1", "symbols": [{"literal":">"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_operator", "symbols": ["comparison_operator$string$1"], "postprocess": id},
    {"name": "comparison_operator", "symbols": [{"literal":"<"}], "postprocess": id},
    {"name": "comparison_operator$string$2", "symbols": [{"literal":"<"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_operator", "symbols": ["comparison_operator$string$2"], "postprocess": id},
    {"name": "comparison_operator$string$3", "symbols": [{"literal":"="}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comparison_operator", "symbols": ["comparison_operator$string$3"], "postprocess": id},
    {"name": "element", "symbols": ["int"], "postprocess": data => {return parseInt(data[0])}},
    {"name": "element", "symbols": ["float"], "postprocess": data => {return parseFloat(data[0])}},
    {"name": "element", "symbols": ["identifier"], "postprocess": id},
    {"name": "element", "symbols": ["expression"], "postprocess": id},
    {"name": "element", "symbols": ["string"], "postprocess": id},
    {"name": "element", "symbols": ["bool"], "postprocess": id},
    {"name": "P", "symbols": [{"literal":"("}, "_", "AS", "_", {"literal":")"}], "postprocess": data => {return data[2]; }},
    {"name": "P", "symbols": ["N"], "postprocess": id},
    {"name": "E", "symbols": ["P", "_", {"literal":"^"}, "_", "E"], "postprocess": data => {return Math.pow(data[0], data[4]); }},
    {"name": "E", "symbols": ["P"], "postprocess": id},
    {"name": "MD", "symbols": ["MD", "_", {"literal":"*"}, "_", "E"], "postprocess": data => {return data[0]*data[4]; }},
    {"name": "MD", "symbols": ["MD", "_", {"literal":"/"}, "_", "E"], "postprocess": data => {return data[0]/data[4]; }},
    {"name": "MD", "symbols": ["E"], "postprocess": id},
    {"name": "AS", "symbols": ["AS", "_", {"literal":"+"}, "_", "MD"], "postprocess": data => {return data[0]+data[4]; }},
    {"name": "AS", "symbols": ["AS", "_", {"literal":"-"}, "_", "MD"], "postprocess": data => {return data[0]-data[4]; }},
    {"name": "AS", "symbols": ["MD"], "postprocess": id},
    {"name": "N", "symbols": ["float"], "postprocess": id},
    {"name": "N$string$1", "symbols": [{"literal":"s"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N", "symbols": ["N$string$1", "_", "P"], "postprocess": data => {return Math.sin(data[2]); }},
    {"name": "N$string$2", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N", "symbols": ["N$string$2", "_", "P"], "postprocess": data => {return Math.cos(data[2]); }},
    {"name": "N$string$3", "symbols": [{"literal":"t"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N", "symbols": ["N$string$3", "_", "P"], "postprocess": data => {return Math.tan(data[2]); }},
    {"name": "N$string$4", "symbols": [{"literal":"a"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N", "symbols": ["N$string$4", "_", "P"], "postprocess": data => {return Math.asin(data[2]); }},
    {"name": "N$string$5", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"o"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N", "symbols": ["N$string$5", "_", "P"], "postprocess": data => {return Math.acos(data[2]); }},
    {"name": "N$string$6", "symbols": [{"literal":"a"}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N", "symbols": ["N$string$6", "_", "P"], "postprocess": data => {return Math.atan(data[2]); }},
    {"name": "N$string$7", "symbols": [{"literal":"p"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N", "symbols": ["N$string$7"], "postprocess": data => {return Math.PI; }},
    {"name": "N", "symbols": [{"literal":"e"}], "postprocess": data => {return Math.E; }},
    {"name": "N$string$8", "symbols": [{"literal":"s"}, {"literal":"q"}, {"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N", "symbols": ["N$string$8", "_", "P"], "postprocess": data => {return Math.sqrt(data[2]); }},
    {"name": "N$string$9", "symbols": [{"literal":"l"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N", "symbols": ["N$string$9", "_", "P"], "postprocess": data => {return Math.log(data[2]); }},
    {"name": "tagname", "symbols": [{"literal":"a"}], "postprocess": id},
    {"name": "tagname$string$1", "symbols": [{"literal":"a"}, {"literal":"b"}, {"literal":"b"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$1"], "postprocess": id},
    {"name": "tagname$string$2", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"y"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$2"], "postprocess": id},
    {"name": "tagname$string$3", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$3"], "postprocess": id},
    {"name": "tagname$string$4", "symbols": [{"literal":"a"}, {"literal":"p"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$4"], "postprocess": id},
    {"name": "tagname$string$5", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$5"], "postprocess": id},
    {"name": "tagname$string$6", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$6"], "postprocess": id},
    {"name": "tagname$string$7", "symbols": [{"literal":"a"}, {"literal":"s"}, {"literal":"i"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$7"], "postprocess": id},
    {"name": "tagname$string$8", "symbols": [{"literal":"a"}, {"literal":"u"}, {"literal":"d"}, {"literal":"i"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$8"], "postprocess": id},
    {"name": "tagname", "symbols": [{"literal":"b"}], "postprocess": id},
    {"name": "tagname$string$9", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$9"], "postprocess": id},
    {"name": "tagname$string$10", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}, {"literal":"f"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$10"], "postprocess": id},
    {"name": "tagname$string$11", "symbols": [{"literal":"b"}, {"literal":"b"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$11"], "postprocess": id},
    {"name": "tagname$string$12", "symbols": [{"literal":"b"}, {"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$12"], "postprocess": id},
    {"name": "tagname$string$13", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$13"], "postprocess": id},
    {"name": "tagname$string$14", "symbols": [{"literal":"b"}, {"literal":"l"}, {"literal":"o"}, {"literal":"c"}, {"literal":"k"}, {"literal":"q"}, {"literal":"u"}, {"literal":"o"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$14"], "postprocess": id},
    {"name": "tagname$string$15", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"d"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$15"], "postprocess": id},
    {"name": "tagname$string$16", "symbols": [{"literal":"b"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$16"], "postprocess": id},
    {"name": "tagname$string$17", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"t"}, {"literal":"t"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$17"], "postprocess": id},
    {"name": "tagname$string$18", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":"v"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$18"], "postprocess": id},
    {"name": "tagname$string$19", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"p"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$19"], "postprocess": id},
    {"name": "tagname$string$20", "symbols": [{"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$20"], "postprocess": id},
    {"name": "tagname$string$21", "symbols": [{"literal":"c"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$21"], "postprocess": id},
    {"name": "tagname$string$22", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$22"], "postprocess": id},
    {"name": "tagname$string$23", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$23"], "postprocess": id},
    {"name": "tagname$string$24", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"l"}, {"literal":"g"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$24"], "postprocess": id},
    {"name": "tagname$string$25", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$25"], "postprocess": id},
    {"name": "tagname$string$26", "symbols": [{"literal":"d"}, {"literal":"a"}, {"literal":"t"}, {"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$26"], "postprocess": id},
    {"name": "tagname$string$27", "symbols": [{"literal":"d"}, {"literal":"a"}, {"literal":"t"}, {"literal":"a"}, {"literal":"l"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$27"], "postprocess": id},
    {"name": "tagname$string$28", "symbols": [{"literal":"d"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$28"], "postprocess": id},
    {"name": "tagname$string$29", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$29"], "postprocess": id},
    {"name": "tagname$string$30", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"t"}, {"literal":"a"}, {"literal":"i"}, {"literal":"l"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$30"], "postprocess": id},
    {"name": "tagname$string$31", "symbols": [{"literal":"d"}, {"literal":"f"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$31"], "postprocess": id},
    {"name": "tagname$string$32", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"a"}, {"literal":"l"}, {"literal":"o"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$32"], "postprocess": id},
    {"name": "tagname$string$33", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$33"], "postprocess": id},
    {"name": "tagname$string$34", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"v"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$34"], "postprocess": id},
    {"name": "tagname$string$35", "symbols": [{"literal":"d"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$35"], "postprocess": id},
    {"name": "tagname$string$36", "symbols": [{"literal":"d"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$36"], "postprocess": id},
    {"name": "tagname$string$37", "symbols": [{"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$37"], "postprocess": id},
    {"name": "tagname$string$38", "symbols": [{"literal":"e"}, {"literal":"m"}, {"literal":"b"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$38"], "postprocess": id},
    {"name": "tagname$string$39", "symbols": [{"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$39"], "postprocess": id},
    {"name": "tagname$string$40", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"d"}, {"literal":"s"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$40"], "postprocess": id},
    {"name": "tagname$string$41", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"g"}, {"literal":"c"}, {"literal":"a"}, {"literal":"p"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$41"], "postprocess": id},
    {"name": "tagname$string$42", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"g"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$42"], "postprocess": id},
    {"name": "tagname$string$43", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$43"], "postprocess": id},
    {"name": "tagname$string$44", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"o"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$44"], "postprocess": id},
    {"name": "tagname$string$45", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$45"], "postprocess": id},
    {"name": "tagname$string$46", "symbols": [{"literal":"f"}, {"literal":"r"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$46"], "postprocess": id},
    {"name": "tagname$string$47", "symbols": [{"literal":"f"}, {"literal":"r"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$47"], "postprocess": id},
    {"name": "tagname$string$48", "symbols": [{"literal":"h"}, {"literal":"1"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$48"], "postprocess": id},
    {"name": "tagname$string$49", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$49"], "postprocess": id},
    {"name": "tagname$string$50", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$50"], "postprocess": id},
    {"name": "tagname$string$51", "symbols": [{"literal":"h"}, {"literal":"g"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$51"], "postprocess": id},
    {"name": "tagname$string$52", "symbols": [{"literal":"h"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$52"], "postprocess": id},
    {"name": "tagname$string$53", "symbols": [{"literal":"h"}, {"literal":"t"}, {"literal":"m"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$53"], "postprocess": id},
    {"name": "tagname", "symbols": [{"literal":"i"}], "postprocess": id},
    {"name": "tagname$string$54", "symbols": [{"literal":"i"}, {"literal":"f"}, {"literal":"r"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$54"], "postprocess": id},
    {"name": "tagname$string$55", "symbols": [{"literal":"i"}, {"literal":"m"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$55"], "postprocess": id},
    {"name": "tagname$string$56", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"p"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$56"], "postprocess": id},
    {"name": "tagname$string$57", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$57"], "postprocess": id},
    {"name": "tagname$string$58", "symbols": [{"literal":"i"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$58"], "postprocess": id},
    {"name": "tagname$string$59", "symbols": [{"literal":"k"}, {"literal":"b"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$59"], "postprocess": id},
    {"name": "tagname$string$60", "symbols": [{"literal":"k"}, {"literal":"e"}, {"literal":"y"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$60"], "postprocess": id},
    {"name": "tagname$string$61", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"b"}, {"literal":"e"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$61"], "postprocess": id},
    {"name": "tagname$string$62", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$62"], "postprocess": id},
    {"name": "tagname$string$63", "symbols": [{"literal":"l"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$63"], "postprocess": id},
    {"name": "tagname$string$64", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$64"], "postprocess": id},
    {"name": "tagname$string$65", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$65"], "postprocess": id},
    {"name": "tagname$string$66", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"r"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$66"], "postprocess": id},
    {"name": "tagname$string$67", "symbols": [{"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$67"], "postprocess": id},
    {"name": "tagname$string$68", "symbols": [{"literal":"m"}, {"literal":"e"}, {"literal":"t"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$68"], "postprocess": id},
    {"name": "tagname$string$69", "symbols": [{"literal":"m"}, {"literal":"e"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$69"], "postprocess": id},
    {"name": "tagname$string$70", "symbols": [{"literal":"n"}, {"literal":"a"}, {"literal":"v"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$70"], "postprocess": id},
    {"name": "tagname$string$71", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"f"}, {"literal":"r"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$71"], "postprocess": id},
    {"name": "tagname$string$72", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"s"}, {"literal":"c"}, {"literal":"r"}, {"literal":"i"}, {"literal":"p"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$72"], "postprocess": id},
    {"name": "tagname$string$73", "symbols": [{"literal":"o"}, {"literal":"b"}, {"literal":"j"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$73"], "postprocess": id},
    {"name": "tagname$string$74", "symbols": [{"literal":"o"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$74"], "postprocess": id},
    {"name": "tagname$string$75", "symbols": [{"literal":"o"}, {"literal":"p"}, {"literal":"t"}, {"literal":"g"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$75"], "postprocess": id},
    {"name": "tagname$string$76", "symbols": [{"literal":"o"}, {"literal":"p"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$76"], "postprocess": id},
    {"name": "tagname$string$77", "symbols": [{"literal":"o"}, {"literal":"u"}, {"literal":"t"}, {"literal":"p"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$77"], "postprocess": id},
    {"name": "tagname", "symbols": [{"literal":"p"}], "postprocess": id},
    {"name": "tagname$string$78", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$78"], "postprocess": id},
    {"name": "tagname$string$79", "symbols": [{"literal":"p"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$79"], "postprocess": id},
    {"name": "tagname$string$80", "symbols": [{"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$80"], "postprocess": id},
    {"name": "tagname", "symbols": [{"literal":"q"}], "postprocess": id},
    {"name": "tagname$string$81", "symbols": [{"literal":"r"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$81"], "postprocess": id},
    {"name": "tagname$string$82", "symbols": [{"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$82"], "postprocess": id},
    {"name": "tagname$string$83", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"b"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$83"], "postprocess": id},
    {"name": "tagname", "symbols": [{"literal":"s"}], "postprocess": id},
    {"name": "tagname$string$84", "symbols": [{"literal":"s"}, {"literal":"a"}, {"literal":"m"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$84"], "postprocess": id},
    {"name": "tagname$string$85", "symbols": [{"literal":"s"}, {"literal":"c"}, {"literal":"r"}, {"literal":"i"}, {"literal":"p"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$85"], "postprocess": id},
    {"name": "tagname$string$86", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$86"], "postprocess": id},
    {"name": "tagname$string$87", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$87"], "postprocess": id},
    {"name": "tagname$string$88", "symbols": [{"literal":"s"}, {"literal":"m"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$88"], "postprocess": id},
    {"name": "tagname$string$89", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$89"], "postprocess": id},
    {"name": "tagname$string$90", "symbols": [{"literal":"s"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$90"], "postprocess": id},
    {"name": "tagname$string$91", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$91"], "postprocess": id},
    {"name": "tagname$string$92", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$92"], "postprocess": id},
    {"name": "tagname$string$93", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"y"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$93"], "postprocess": id},
    {"name": "tagname$string$94", "symbols": [{"literal":"s"}, {"literal":"u"}, {"literal":"b"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$94"], "postprocess": id},
    {"name": "tagname$string$95", "symbols": [{"literal":"s"}, {"literal":"u"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$95"], "postprocess": id},
    {"name": "tagname$string$96", "symbols": [{"literal":"t"}, {"literal":"a"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$96"], "postprocess": id},
    {"name": "tagname$string$97", "symbols": [{"literal":"t"}, {"literal":"b"}, {"literal":"o"}, {"literal":"d"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$97"], "postprocess": id},
    {"name": "tagname$string$98", "symbols": [{"literal":"t"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$98"], "postprocess": id},
    {"name": "tagname$string$99", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$99"], "postprocess": id},
    {"name": "tagname$string$100", "symbols": [{"literal":"t"}, {"literal":"f"}, {"literal":"o"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$100"], "postprocess": id},
    {"name": "tagname$string$101", "symbols": [{"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$101"], "postprocess": id},
    {"name": "tagname$string$102", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$102"], "postprocess": id},
    {"name": "tagname$string$103", "symbols": [{"literal":"t"}, {"literal":"i"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$103"], "postprocess": id},
    {"name": "tagname$string$104", "symbols": [{"literal":"t"}, {"literal":"i"}, {"literal":"t"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$104"], "postprocess": id},
    {"name": "tagname$string$105", "symbols": [{"literal":"t"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$105"], "postprocess": id},
    {"name": "tagname$string$106", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$106"], "postprocess": id},
    {"name": "tagname$string$107", "symbols": [{"literal":"t"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$107"], "postprocess": id},
    {"name": "tagname", "symbols": [{"literal":"u"}], "postprocess": id},
    {"name": "tagname$string$108", "symbols": [{"literal":"u"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$108"], "postprocess": id},
    {"name": "tagname$string$109", "symbols": [{"literal":"v"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$109"], "postprocess": id},
    {"name": "tagname$string$110", "symbols": [{"literal":"v"}, {"literal":"i"}, {"literal":"d"}, {"literal":"e"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$110"], "postprocess": id},
    {"name": "tagname$string$111", "symbols": [{"literal":"w"}, {"literal":"b"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tagname", "symbols": ["tagname$string$111"], "postprocess": id},
    {"name": "statement$ebnf$1", "symbols": []},
    {"name": "statement$ebnf$1", "symbols": ["statement$ebnf$1", "instructions"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "statement$ebnf$2", "symbols": []},
    {"name": "statement$ebnf$2", "symbols": ["statement$ebnf$2", "statement"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "statement", "symbols": [{"literal":"$"}, "tagname", "__", "class", "_", {"literal":"{"}, "_", "statement$ebnf$1", "_", "statement$ebnf$2", "_", {"literal":"}"}, "_", {"literal":";"}, "_"], "postprocess": 
        d => {
            return {
                type:"tag",
                tagname: d[1],
                class: d[3],
                instructions: d[7],
                sub_tags: d[9]
            }
        }
        },
    {"name": "instructions", "symbols": ["attribut", "_", /[=|:]/, "_", "value_with_unity", "_", {"literal":";"}, "_"], "postprocess":  
        d => { switch(d[2]){
            case "=": return(( d[0] + "=" + d[4]).toString())
            case ":": return((d[0] + ":" + d[4]).toString())
        }
        }
        },
    {"name": "attribut$ebnf$1", "symbols": [/[a-zA-Z0-9_-]/]},
    {"name": "attribut$ebnf$1", "symbols": ["attribut$ebnf$1", /[a-zA-Z0-9_-]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "attribut", "symbols": ["attribut$ebnf$1"], "postprocess": d => d[0].join("")},
    {"name": "class$ebnf$1", "symbols": [/[a-zA-Z0-9_]/]},
    {"name": "class$ebnf$1", "symbols": ["class$ebnf$1", /[a-zA-Z0-9_]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "class", "symbols": [/[.]/, "class$ebnf$1"], "postprocess": d => d[1].join("")},
    {"name": "value_with_unity$subexpression$1$string$1", "symbols": [{"literal":"p"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "value_with_unity$subexpression$1", "symbols": ["value_with_unity$subexpression$1$string$1"]},
    {"name": "value_with_unity$subexpression$1$string$2", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "value_with_unity$subexpression$1", "symbols": ["value_with_unity$subexpression$1$string$2"]},
    {"name": "value_with_unity$subexpression$1$string$3", "symbols": [{"literal":"p"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "value_with_unity$subexpression$1", "symbols": ["value_with_unity$subexpression$1$string$3"]},
    {"name": "value_with_unity$subexpression$1", "symbols": [{"literal":"%"}]},
    {"name": "value_with_unity", "symbols": ["identifier", "_", "value_with_unity$subexpression$1"], "postprocess": d => d[0] + d[2]},
    {"name": "value_with_unity$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "value_with_unity$ebnf$1", "symbols": ["value_with_unity$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "value_with_unity$subexpression$2$string$1", "symbols": [{"literal":"p"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "value_with_unity$subexpression$2", "symbols": ["value_with_unity$subexpression$2$string$1"]},
    {"name": "value_with_unity$subexpression$2$string$2", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "value_with_unity$subexpression$2", "symbols": ["value_with_unity$subexpression$2$string$2"]},
    {"name": "value_with_unity$subexpression$2$string$3", "symbols": [{"literal":"p"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "value_with_unity$subexpression$2", "symbols": ["value_with_unity$subexpression$2$string$3"]},
    {"name": "value_with_unity$subexpression$2", "symbols": [{"literal":"%"}]},
    {"name": "value_with_unity", "symbols": ["value_with_unity$ebnf$1", "_", "value_with_unity$subexpression$2"], "postprocess": d => d[0].join("") + d[2]},
    {"name": "value_with_unity", "symbols": ["string"], "postprocess": id},
    {"name": "value_with_unity$subexpression$3$string$1", "symbols": [{"literal":"p"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "value_with_unity$subexpression$3", "symbols": ["value_with_unity$subexpression$3$string$1"]},
    {"name": "value_with_unity$subexpression$3$string$2", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "value_with_unity$subexpression$3", "symbols": ["value_with_unity$subexpression$3$string$2"]},
    {"name": "value_with_unity$subexpression$3$string$3", "symbols": [{"literal":"p"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "value_with_unity$subexpression$3", "symbols": ["value_with_unity$subexpression$3$string$3"]},
    {"name": "value_with_unity$subexpression$3", "symbols": [{"literal":"%"}]},
    {"name": "value_with_unity", "symbols": ["expression", "_", "value_with_unity$subexpression$3"], "postprocess": d => d[0] + d[2]},
    {"name": "value_with_unity$ebnf$2", "symbols": [/[0-9A-Fa-f]/]},
    {"name": "value_with_unity$ebnf$2", "symbols": ["value_with_unity$ebnf$2", /[0-9A-Fa-f]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "value_with_unity", "symbols": [{"literal":"#"}, "value_with_unity$ebnf$2"], "postprocess": d => d[0] + d[1].join("")},
    {"name": "assignment", "symbols": ["identifier", "_", {"literal":"="}, "_", "value", "_", {"literal":";"}], "postprocess": 
        d => ({
            type:"assignment",
            identifier:d[0],
            value:d[4]
        })
        },
    {"name": "include$string$1", "symbols": [{"literal":"@"}, {"literal":"i"}, {"literal":"n"}, {"literal":"c"}, {"literal":"l"}, {"literal":"u"}, {"literal":"d"}, {"literal":"e"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "include", "symbols": ["include$string$1", "link", {"literal":")"}, "_", {"literal":";"}], "postprocess": 
        d => ({
            type:"include",
            link: d[1]
        })
        },
    {"name": "link", "symbols": ["characters"], "postprocess": id},
    {"name": "link", "symbols": ["identifier"], "postprocess": id},
    {"name": "use$string$1", "symbols": [{"literal":"@"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "use", "symbols": ["use$string$1", "link", {"literal":")"}, "_", {"literal":";"}], "postprocess": 
        d => ({
            type:"use",
            link: d[1]
        })
        },
    {"name": "link", "symbols": ["string"], "postprocess": id},
    {"name": "link", "symbols": ["identifier"], "postprocess": id},
    {"name": "comment$string$1", "symbols": [{"literal":"\\"}, {"literal":"\\"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comment", "symbols": ["comment$string$1", "_", "characters"], "postprocess":  d => { 
            return{
                type:"comment",
                text:d[2]
            }
        }
        },
    {"name": "js_and_php$string$1", "symbols": [{"literal":"#"}, {"literal":"j"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "js_and_php$string$2", "symbols": [{"literal":"#"}, {"literal":"j"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "js_and_php", "symbols": ["js_and_php$string$1", "_", "special_characters", "_", "js_and_php$string$2"], "postprocess": 
        d => {
           return{
               type:"js",
               code:d[2]
           } 
        }
        },
    {"name": "js_and_php$string$3", "symbols": [{"literal":"#"}, {"literal":"p"}, {"literal":"h"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "js_and_php$string$4", "symbols": [{"literal":"#"}, {"literal":"p"}, {"literal":"h"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "js_and_php", "symbols": ["js_and_php$string$3", "_", "special_characters", "_", "js_and_php$string$4"], "postprocess": 
        d => {
           return{
               type:"php",
               code:d[2]
           } 
        }
        },
    {"name": "js_and_php$string$5", "symbols": [{"literal":"#"}, {"literal":"h"}, {"literal":"t"}, {"literal":"m"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "js_and_php$string$6", "symbols": [{"literal":"#"}, {"literal":"h"}, {"literal":"t"}, {"literal":"m"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "js_and_php", "symbols": ["js_and_php$string$5", "_", "special_characters", "_", "js_and_php$string$6"], "postprocess": 
        d => {
           return{
               type:"html",
               code:d[2]
           } 
        }
        },
    {"name": "special_characters$ebnf$1$subexpression$1", "symbols": ["character"]},
    {"name": "special_characters$ebnf$1$subexpression$1", "symbols": [/[/";]/]},
    {"name": "special_characters$ebnf$1", "symbols": ["special_characters$ebnf$1$subexpression$1"]},
    {"name": "special_characters$ebnf$1$subexpression$2", "symbols": ["character"]},
    {"name": "special_characters$ebnf$1$subexpression$2", "symbols": [/[/";]/]},
    {"name": "special_characters$ebnf$1", "symbols": ["special_characters$ebnf$1", "special_characters$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "special_characters", "symbols": ["special_characters$ebnf$1"], "postprocess": d => d[0].join("")},
    {"name": "program", "symbols": ["assignment"], "postprocess": id},
    {"name": "program", "symbols": ["statement"], "postprocess": id},
    {"name": "program", "symbols": ["include"], "postprocess": id},
    {"name": "program", "symbols": ["use"], "postprocess": id},
    {"name": "program", "symbols": ["expression"], "postprocess": id},
    {"name": "program", "symbols": ["comment"], "postprocess": id},
    {"name": "program", "symbols": ["js_and_php"], "postprocess": id},
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", /[ \r\t\n,]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": d => null},
    {"name": "__$ebnf$1", "symbols": [/[ \r\t\n,]/]},
    {"name": "__$ebnf$1", "symbols": ["__$ebnf$1", /[ \r\t\n,]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__", "symbols": ["__$ebnf$1"], "postprocess": d => null}
]
  , ParserStart: "program"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
